<?php

return [
    'accepted' => ':attribute 必须被接受。',
    'accepted_if' => ':other 为 :value 时，必须接受 :attribute。',
    'active_url' => ':attribute 不是一个有效的 URL。',
    'after' => ':attribute 必须是一个在 :date 之后的日期。',
    'after_or_equal' => ':attribute 必须是一个在 :date 之后或等于 :date 的日期。',
    'alpha' => ':attribute 只能包含字母。',
    'alpha_dash' => ':attribute 只能包含字母、数字、破折号和下划线。',
    'alpha_num' => ':attribute 只能包含字母和数字。',
    'array' => ':attribute 必须是一个数组。',
    'ascii' => ':attribute 字段只能包含单字节的字母数字字符和符号。',
    'before' => ':attribute 必须是 :date 之前的日期。',
    'before_or_equal' => ':attribute 必须是一个在 :date 之前或等于 :date 的日期。',
    'between' => [
        'array' => ':attribute 必须有 :min 到 :max 个项目。',
        'file' => ':attribute 必须在 :min 和 :max 千字节之间。',
        'numeric' => ':attribute 必须在 :min 和 :max 之间。',
        'string' => ':attribute 必须在 :min 和 :max 个字符之间。',
    ],
    'boolean' => ':attribute 字段必须为真或假。',
    'can' => ':attribute 字段包含一个未经授权的值。',
    'confirmed' => ':attribute 确认不匹配。',
    'contains' => ':attribute 字段缺少必填值。',
    'current_password' => '密码不正确。',
    'date' => ':attribute 不是一个有效的日期。',
    'date_equals' => ':attribute 必须是等于 :date 的日期。',
    'date_format' => ':attribute 不符合格式 :format。',
    'decimal' => ':attribute 字段必须有 :decimal 位小数。',
    'declined' => ':attribute 必须被拒绝。',
    'declined_if' => ':attribute 必须在 :other 为 :value 时被拒绝。',
    'different' => ':attribute 和 :other 必须不同。',
    'digits' => ':attribute 必须是 :digits 位数字。',
    'digits_between' => ':attribute 必须在 :min 和 :max 位数之间。',
    'dimensions' => ':attribute 的图像尺寸无效。',
    'distinct' => ':attribute 字段有重复值。',
    'doesnt_end_with' => ':attribute 字段不得以以下之一结尾：:values。',
    'doesnt_start_with' => ':attribute 不能以以下之一开头: :values。',
    'email' => ':attribute 必须是一个有效的电子邮件地址。',
    'ends_with' => ':attribute 必须以以下之一结尾：:values。',
    'enum' => '所选的 :attribute 无效。',
    'exists' => '所选的 :attribute 无效。',
    'extensions' => ':attribute 字段必须具有以下扩展名之一：:values。',
    'file' => ':attribute 必须是一个文件。',
    'filled' => ':attribute 字段必须有一个值。',
    'gt' => [
        'array' => ':attribute 必须有超过 :value 项。',
        'file' => ':attribute 必须大于 :value 千字节。',
        'numeric' => ':attribute 必须大于 :value。',
        'string' => ':attribute 必须大于 :value 个字符。',
    ],
    'gte' => [
        'array' => ':attribute 必须有 :value 个或更多项目。',
        'file' => ':attribute 必须大于或等于 :value 千字节。',
        'numeric' => ':attribute 必须大于或等于 :value。',
        'string' => ':attribute 必须大于或等于 :value 个字符。',
    ],
    'hex_color' => ':attribute 字段必须是有效的十六进制颜色。',
    'image' => ':attribute 必须是一个图像。',
    'in' => '所选的 :attribute 无效。',
    'in_array' => ':other 中不存在 :attribute 字段。',
    'integer' => ':attribute 必须是一个整数。',
    'ip' => ':attribute 必须是一个有效的 IP 地址。',
    'ipv4' => ':attribute 必须是一个有效的 IPv4 地址。',
    'ipv6' => ':attribute 必须是一个有效的 IPv6 地址。',
    'json' => ':attribute 必须是一个有效的 JSON 字符串。',
    'list' => ':attribute 字段必须是一个列表。',
    'lowercase' => ':attribute 字段必须是小写。',
    'lt' => [
        'array' => ':attribute 必须少于 :value 项。',
        'file' => ':attribute 必须小于 :value 千字节。',
        'numeric' => ':attribute 必须小于 :value。',
        'string' => ':attribute 必须少于 :value 个字符。',
    ],
    'lte' => [
        'array' => ':attribute 不能有超过 :value 项。',
        'file' => ':attribute 必须小于或等于 :value 千字节。',
        'numeric' => ':attribute 必须小于或等于 :value。',
        'string' => ':attribute 必须小于或等于 :value 个字符。',
    ],
    'mac_address' => ':attribute 必须是一个有效的 MAC 地址。',
    'max' => [
        'array' => ':attribute 不能超过 :max 项。',
        'file' => ':attribute 不能大于 :max 千字节。',
        'numeric' => ':attribute 不能大于 :max。',
        'string' => ':attribute 不能超过 :max 个字符。',
    ],
    'max_digits' => ':attribute 字段不得超过 :max 位数字。',
    'mimes' => ':attribute 必须是类型为 :values 的文件。',
    'mimetypes' => ':attribute 必须是类型为 :values 的文件。',
    'min' => [
        'array' => ':attribute 必须至少有 :min 项。',
        'file' => ':attribute 必须至少为 :min 千字节。',
        'numeric' => ':attribute 必须至少为 :min。',
        'string' => ':attribute 必须至少为 :min 个字符。',
    ],
    'min_digits' => ':attribute 字段必须至少有 :min 位数字。',
    'missing' => ':attribute 字段必须缺失。',
    'missing_if' => ':attribute 字段在 :other 为 :value 时必须缺失。',
    'missing_unless' => ':attribute 字段必须缺失，除非 :other 是 :value。',
    'missing_with' => ':attribute 字段在 :values 存在时必须缺失。',
    'missing_with_all' => ':attribute 字段在 :values 存在时必须缺失。',
    'multiple_of' => ':attribute 必须是 :value 的倍数。',
    'not_in' => '所选的 :attribute 无效。',
    'not_regex' => ':attribute 格式无效。',
    'numeric' => ':attribute 必须是一个数字。',
    'password' => [
        'mixed' => ':attribute 必须至少包含一个大写字母和一个小写字母。',
        'numbers' => ':attribute 必须至少包含一个数字。',
        'symbols' => ':attribute 必须至少包含一个符号。',
        'uncompromised' => '给定的 :attribute 已出现在数据泄露中。请选用其他 :attribute。',
        'letters' => ':attribute 必须至少包含一个字母。',
    ],
    'present' => ':attribute 字段必须存在。',
    'present_if' => ':attribute 字段在 :other 为 :value 时必须存在。',
    'present_unless' => ':attribute 字段必须存在，除非 :other 是 :value。',
    'present_with' => ':values 存在时，:attribute 字段必须存在。',
    'present_with_all' => ':attribute 字段在 :values 存在时必须存在。',
    'prohibited' => ':attribute 字段是禁止的。',
    'prohibited_if' => ':attribute 字段在 :other 为 :value 时被禁止。',
    'prohibited_unless' => ':attribute 字段是禁止的，除非 :other 在 :values 中。',
    'prohibits' => ':attribute 字段禁止 :other 存在。',
    'regex' => ':attribute 格式无效。',
    'required' => ':attribute 字段是必需的。',
    'required_array_keys' => ':attribute 字段必须包含以下条目：:values。',
    'required_if' => ':attribute 字段是必需的，当 :other 是 :value。',
    'required_if_accepted' => ':attribute 字段是必需的，当接受 :other 时。',
    'required_if_declined' => ':attribute 字段在拒绝 :other 时是必需的。',
    'required_unless' => ':attribute 字段是必需的，除非 :other 在 :values 中。',
    'required_with' => ':values 存在时，:attribute 字段是必需的。',
    'required_with_all' => ':attribute 字段在 :values 存在时是必需的。',
    'required_without' => ':attribute 字段是必需的，当 :values 不存在时。',
    'required_without_all' => ':attribute 字段是必需的，当 :values 都不存在时。',
    'same' => ':attribute 和 :other 必须匹配。',
    'size' => [
        'array' => ':attribute 必须包含 :size 项。',
        'file' => ':attribute 必须是 :size 千字节。',
        'numeric' => ':attribute 必须是 :size。',
        'string' => ':attribute 必须是 :size 个字符。',
    ],
    'starts_with' => ':attribute 必须以以下之一开头：:values。',
    'string' => ':attribute 必须是一个字符串。',
    'timezone' => ':attribute 必须是一个有效的时区。',
    'unique' => ':attribute 已被占用。',
    'uploaded' => ':attribute 上传失败。',
    'uppercase' => ':attribute 字段必须是大写。',
    'url' => ':attribute 必须是一个有效的 URL。',
    'ulid' => ':attribute 字段必须是一个有效的 ULID。',
    'uuid' => ':attribute 必须是一个有效的 UUID。',
    'custom' => [
        'attribute-name' => [
            'rule-name' => '自定义消息',
        ],
    ],
    'attributes' => [],
];
