<?php

return [
    'accepted' => 'Le :attribute doit être acceptée.',
    'accepted_if' => 'Le :attribute doit être acceptée lorsque :other is :value.',
    'active_url' => 'Le :attribute n\'est pas une URL valide..',
    'after' => 'Le :attribute doit être une date postérieure à :date',
    'after_or_equal' => 'Le :attribute doit être une date postérieure ou égale à :date.',
    'alpha' => 'Le :attribute ne peut contenir que des lettres',
    'alpha_dash' => 'Le :attribute ne doit contenir que des lettres, des chiffres, des tirets et des traits de soulignement.',
    'alpha_num' => 'Le :attribute ne doit contenir que des lettres et des chiffres.',
    'array' => 'Le :attribute doit être un tableau.',
    'before' => 'Le :attribute doit être une date avant :date.',
    'before_or_equal' => 'Le :attribute doit être une date antérieure ou égale à :date.',
    'between' => [
        'array' => 'Le :attribute doit comporter entre :min et :max.',
        'file' => 'Le :attribute doit être compris entre :min et :max kilo-octets.',
        'numeric' => 'Le :attribute doit être compris entre :min et :max.',
        'string' => 'Le :attribute doit être compris entre les caractères :min et :max.',
    ],
    'boolean' => 'Le champ :attribute doit avoir la valeur true ou false.',
    'confirmed' => 'Le :attribute La confirmation ne correspond pas.',
    'current_password' => 'Le mot de passe est incorrect.',
    'date' => 'Le :attribute n\'est pas une date valide.',
    'date_equals' => 'Le :attribute doit être une date égale à :date.',
    'date_format' => 'Le :attribute ne correspond pas au format :format.',
    'declined' => 'Le :attribute doit être décliné.',
    'declined_if' => 'Le :attribute attribute doit être décliné lorsque :other est :value.',
    'different' => 'Le  :attribute et :other doivent être différents.',
    'digits' => 'Le :attribute doit être :digits chiffres.',
    'digits_between' => 'Le :attribute doit être compris entre les chiffres :min et :max.',
    'dimensions' => 'Le :attribute a des dimensions d\'image non valides.',
    'distinct' => 'Le champ :attribute a une valeur en double.',
    'doesnt_end_with' => 'Le :attribute ne peut pas se terminer par l\'un des éléments suivants : :values..',
    'doesnt_start_with' => 'Le :attribute ne peut pas commencer par l\'un des éléments suivants : :values.',
    'email' => 'Le :attribute doit être une adresse e-mail valide.',
    'ends_with' => 'Le :attribute doit se terminer par l\'un des éléments suivants : :values..',
    'enum' => 'L\'option sélectionnée :attribute n\'est pas valide.',
    'exists' => 'L\'option sélectionnée :attribute n\'est pas valide.',
    'file' => 'Le :attribute doit être un fichier.',
    'filled' => 'Le :attribute doit avoir une valeur.',
    'gt' => [
        'array' => 'Le :attribute doit avoir plus d\'éléments :value.',
        'file' => 'Le :attribute doit être supérieur à la :value kilo-octets.',
        'numeric' => 'Le :attribute doit être supérieur à :value.',
        'string' => 'Le :attribute doit être supérieur à :value caractères.',
    ],
    'gte' => [
        'array' => 'Le :attribute doit avoir des éléments :value ou plus..',
        'file' => 'Le :attribute doit être supérieur ou égal à :value kilobytes.',
        'numeric' => 'Le :attribute doit être supérieur ou égal à :value.',
        'string' => 'Le :attribute doit être supérieur ou égal à :value caractères.',
    ],
    'image' => 'Le :attribute doit être une image.',
    'in' => 'L\'option sélectionnée :attribute n\'est pas valide.',
    'in_array' => 'Le :attribute n\'existe pas dans le champ :other.',
    'integer' => 'Le :attribute doit être un nombre entier.',
    'ip' => 'Le :attribute doit être une adresse IP valide.',
    'ipv4' => 'Le :attribute doit être une adresse IPv4 valide.',
    'ipv6' => 'Le :attribute doit être une adresse IPv6 valide.',
    'json' => 'Le :attribute doit être une chaîne JSON valide.',
    'lowercase' => 'Le :attribute doit être en minuscules.',
    'lt' => [
        'array' => 'Le :attribute doit avoir moins de :value objets.',
        'file' => 'Le :attribute doit être inférieur à :value kilobytes.',
        'numeric' => 'Le :attribute doit être inférieur à :value.',
        'string' => 'Le :attribute doit être inférieur à :value caractères.',
    ],
    'lte' => [
        'array' => 'Le :attribute ne doit pas comporter plus de :value objets.',
        'file' => 'Le :attribute doit être inférieur ou égal à :value kilobytes.',
        'numeric' => 'Le :attribute doit être inférieur ou égal à :value.',
        'string' => 'Le :attribute doit être inférieur ou égal à :value caractères.',
    ],
    'mac_address' => 'Le :attribute doit être une adresse MAC valide.',
    'max' => [
        'array' => 'Le :attribute ne doit pas comporter plus de :max items.',
        'file' => 'Le :attribute ne doit pas être supérieur à :max kilobytes.',
        'numeric' => 'Le :attribute ne doit pas être supérieur à :max.',
        'string' => 'Le :attribute ne doit pas être supérieur à :max characters.',
    ],
    'max_digits' => 'Le :attribute ne doit pas comporter plus de :max digits.',
    'mimes' => 'Le :attribute doit être un fichier de type: :values.',
    'mimetypes' => 'Le :attribute doit être un fichier de type: :values.',
    'min' => [
        'array' => 'The :attribute doit avoir au moins :min items.',
        'file' => 'Le :attribute doit être d\'au moins :min kilobytes.',
        'numeric' => 'Le :attribute doit être d\'au moins :min.',
        'string' => 'Le :attribute doit être d\'au moins :min caractères.',
    ],
    'min_digits' => 'Le :attribute doit avoir au moins :min digits.',
    'multiple_of' => 'Le :attribute doit être un multiple de :value.',
    'not_in' => 'L\'option sélectionnée :attribute n\'est pas valide.',
    'not_regex' => 'Le :attribute  format n\'est pas valide.',
    'numeric' => 'Le :attribute doit être un nombre.',
    'password' => [
        'letters' => 'The :attribute doit contenir au moins une lettre.',
        'mixed' => 'Le :attribute doit contenir au moins une lettre majuscule et une lettre minuscule.',
        'numbers' => 'Le :attribute doit contenir au moins un nombre.',
        'symbols' => 'Le :attribute doit contenir au moins un symbole.',
        'uncompromised' => 'Les données :attribute sont apparu dans une fuite de données. Veuillez choisir un autre :attribut.',
    ],
    'present' => 'Le :attribute doit être présent.',
    'prohibited' => 'Le  :attribute est interdite.',
    'prohibited_if' => 'Le :attribute est interdit lorsque :other est :value.',
    'prohibited_unless' => 'Le :attribute est interdit à moins que :other ne figure dans :values.',
    'prohibits' => 'Le :attribute le champ interdit :other d\'être présent.',
    'regex' => 'Le :attribute le format n\'est pas valide.',
    'required' => 'Le :attribute est obligatoire.',
    'required_array_keys' => 'Le :attribute doit contenir des entrées pour: :values.',
    'required_if' => 'Le :attribute Le champ est obligatoire lorsque :other is :value.',
    'required_if_accepted' => 'Le  :attribute Le champ est obligatoire lorsque :other est acceptée.',
    'required_unless' => 'Le :attribute Le champ est obligatoire sauf si :other est en :values.',
    'required_with' => 'Le :attribute Le champ est obligatoire lorsque :values est présent.',
    'required_with_all' => 'Le :attribute Le champ est obligatoire lorsque :values sont présents.',
    'required_without' => 'Le :attribute Le champ est obligatoire lorsque :values n\'est pas présent.',
    'required_without_all' => 'Le :attribute field is required when none of :values are present.',
    'same' => 'Le :attribute et :other doit correspondre.',
    'size' => [
        'array' => 'Le :attribute doit contenir :size items.',
        'file' => 'Le :attribute doit être :size kilobytes.',
        'numeric' => 'Le :attribute doit être :size.',
        'string' => 'Le :attribute doit être :size caractères.',
    ],
    'starts_with' => 'Le :attribute doit commencer par l\'un des éléments suivants : :values.',
    'string' => 'Le :attribute doit être une chaîne de caractères.',
    'timezone' => 'Le :attribute doit être un fuseau horaire valide.',
    'unique' => 'Le :attribute a déjà été prise.',
    'uploaded' => 'Le :attribute n\'a pas pu être téléchargé.',
    'url' => 'Le :attribute doit être un URL.',
    'uuid' => 'Le  :attribute doit être un UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'message personnalisé',
        ],
    ],
];
