<?php

return [
    'accepted' => ':attribute 必須被接受。',
    'accepted_if' => ':attribute 必須在 :other 是 :value 時被接受。',
    'active_url' => ':attribute 不是有效的 URL。',
    'after' => ':attribute 必須是一個在 :date 之後的日期。',
    'after_or_equal' => ':attribute 必須是一個在 :date 之後或等於 :date 的日期。',
    'alpha' => ':attribute 只可以包含字母。',
    'alpha_dash' => ':attribute 只可以包含字母、數字、短橫和底線。',
    'alpha_num' => ':attribute 只可以包含字母和數字。',
    'array' => ':attribute 必須是一個數組。',
    'ascii' => ':attribute 字段只可以包含單字節的字母數字字符和符號。',
    'before' => ':attribute 必須是一個在 :date 之前的日期。',
    'before_or_equal' => ':attribute 必須是一個在 :date 之前或等於 :date 的日期。',
    'between' => [
        'array' => ':attribute 必須有介乎 :min 和 :max 之間的項目。',
        'file' => ':attribute 必須介乎 :min 和 :max 千字節之間。',
        'numeric' => ':attribute 必須介乎 :min 和 :max 之間。',
        'string' => ':attribute 必須介乎 :min 和 :max 個字符之間。',
    ],
    'boolean' => ':attribute 字段必須為真或假。',
    'can' => ':attribute 欄位包含未經授權的值。',
    'confirmed' => ':attribute 確認不匹配。',
    'contains' => ':attribute 欄位缺少一個必需的值。',
    'current_password' => '密碼不正確。',
    'date' => ':attribute 不是有效的日期。',
    'date_equals' => ':attribute 必須是一個等於 :date 的日期。',
    'date_format' => ':attribute 與格式 :format 不匹配。',
    'decimal' => ':attribute 字段必須有 :decimal 位小數。',
    'declined' => ':attribute 必須被拒絕。',
    'declined_if' => ':attribute 必須在 :other 是 :value 時拒絕。',
    'different' => ':attribute 和 :other 必須不同。',
    'digits' => ':attribute 必須是 :digits 位數。',
    'digits_between' => ':attribute 必須介乎 :min 和 :max 位數之間。',
    'dimensions' => ':attribute 的圖像尺寸無效。',
    'distinct' => ':attribute 字段有重複的值。',
    'doesnt_end_with' => ':attribute 字段唔可以以以下其中一個結尾：:values。',
    'doesnt_start_with' => ':attribute 不能以以下其中一個開始: :values。',
    'email' => ':attribute 必須是一個有效的電子郵件地址。',
    'ends_with' => ':attribute 必須以以下其中一個結尾：:values。',
    'enum' => '所選的 :attribute 是無效的。',
    'exists' => '所選的 :attribute 是無效的。',
    'extensions' => ':attribute 欄位必須具有以下其中一種擴展名：:values。',
    'file' => ':attribute 必須是一個文件。',
    'filled' => ':attribute 欄位必須有一個值。',
    'gt' => [
        'array' => ':attribute 必須有超過 :value 個項目。',
        'file' => ':attribute 必須大於 :value 千位元組。',
        'numeric' => ':attribute 必須大於 :value。',
        'string' => ':attribute 必須大於 :value 個字符。',
    ],
    'gte' => [
        'array' => ':attribute 必須有 :value 個或更多項目。',
        'file' => ':attribute 必須大於或等於 :value 千字節。',
        'numeric' => ':attribute 必須大於或等於 :value。',
        'string' => ':attribute 必須大於或等於 :value 個字符。',
    ],
    'hex_color' => ':attribute 字段必須是一個有效的十六進制顏色。',
    'image' => ':attribute 必須是一張圖片。',
    'in' => '所選的 :attribute 是無效的。',
    'in_array' => ':other 裡面不存在 :attribute 欄位。',
    'integer' => ':attribute 必須是一個整數。',
    'ip' => ':attribute 必須是一個有效的 IP 地址。',
    'ipv4' => ':attribute 必須是一個有效的 IPv4 地址。',
    'ipv6' => ':attribute 必須是一個有效的 IPv6 地址。',
    'json' => ':attribute 必須是一個有效的 JSON 字串。',
    'list' => ':attribute 字段必須是一個列表。',
    'lowercase' => ':attribute 欄位必須是小寫字母。',
    'lt' => [
        'array' => ':attribute 必須少於 :value 個項目。',
        'file' => ':attribute 必須少於 :value 千位元組。',
        'numeric' => ':attribute 必須少於 :value。',
        'string' => ':attribute 必須少於 :value 個字符。',
    ],
    'lte' => [
        'array' => ':attribute 不能有超過 :value 個項目。',
        'file' => ':attribute 必須小於或等於 :value 千字節。',
        'numeric' => ':attribute 必須小於或等於 :value。',
        'string' => ':attribute 必須少於或等於 :value 個字符。',
    ],
    'mac_address' => ':attribute 必須是一個有效的 MAC 地址。',
    'max' => [
        'array' => ':attribute 不能有超過 :max 個項目。',
        'file' => ':attribute 不能大於 :max 千字節。',
        'numeric' => ':attribute 不能大於 :max。',
        'string' => ':attribute 不能超過 :max 個字符。',
    ],
    'max_digits' => ':attribute 字段不得超過 :max 位數。',
    'mimes' => ':attribute 必須是一個類型為 :values 的文件。',
    'mimetypes' => ':attribute 必須是一個類型為 :values 的文件。',
    'min' => [
        'array' => ':attribute 必須至少有 :min 個項目。',
        'file' => ':attribute 必須至少為 :min 千字節。',
        'numeric' => ':attribute 必須至少為 :min。',
        'string' => ':attribute 必須至少有 :min 個字符。',
    ],
    'min_digits' => ':attribute 欄位必須至少有 :min 位數。',
    'missing' => ':attribute 欄位必須缺失。',
    'missing_if' => ':attribute 字段必須在 :other 為 :value 時缺失。',
    'missing_unless' => ':attribute 字段必須缺失，除非 :other 是 :value。',
    'missing_with' => ':attribute 字段必須在 :values 存在時缺失。',
    'missing_with_all' => ':attribute 字段必須在 :values 存在時缺失。',
    'multiple_of' => ':attribute 必須是 :value 的倍數。',
    'not_in' => '所選的 :attribute 是無效的。',
    'not_regex' => ':attribute 格式無效。',
    'numeric' => ':attribute 必須是一個數字。',
    'password' => [
        'letters' => ':attribute 必須包含至少一個字母。',
        'mixed' => ':attribute 必須包含至少一個大寫字母和一個小寫字母。',
        'numbers' => ':attribute 必須包含至少一個數字。',
        'symbols' => ':attribute 必須包含至少一個符號。',
        'uncompromised' => '所提供的 :attribute 已經出現在數據洩漏中。請選擇另一個 :attribute。',
    ],
    'present' => ':attribute 欄位必須存在。',
    'present_if' => ':attribute 字段必須在 :other 為 :value 時存在。',
    'present_unless' => ':attribute 字段必須存在，除非 :other 是 :value。',
    'present_with' => ':attribute 字段必須在 :values 存在時出現。',
    'present_with_all' => ':attribute 字段必須在 :values 存在時出現。',
    'prohibited' => ':attribute 字段是禁止的。',
    'prohibited_if' => ':attribute 字段在 :other 為 :value 時是禁止的。',
    'prohibited_unless' => ':attribute 字段是禁止的，除非 :other 在 :values 中。',
    'prohibits' => ':attribute 字段禁止 :other 存在。',
    'regex' => ':attribute 格式無效。',
    'required' => ':attribute 欄位是必需的。',
    'required_array_keys' => ':attribute 欄位必須包含以下項目的輸入：:values。',
    'required_if' => ':attribute 字段是必需的，當 :other 是 :value。',
    'required_if_accepted' => ':attribute 字段是必需的，當接受 :other 時。',
    'required_if_declined' => ':attribute 字段是必需的，當 :other 被拒絕時。',
    'required_unless' => ':attribute 字段是必需的，除非 :other 在 :values 中。',
    'required_with' => ':attribute 字段係必需嘅，當 :values 存在時。',
    'required_with_all' => ':attribute 字段在 :values 存在時是必需的。',
    'required_without' => ':attribute 字段是必需的，當 :values 不存在時。',
    'required_without_all' => ':attribute 字段是必需的，當 :values 全部不存在時。',
    'same' => ':attribute 和 :other 必須相符。',
    'size' => [
        'array' => ':attribute 必須包含 :size 個項目。',
        'file' => ':attribute 必須是 :size 千字節。',
        'numeric' => ':attribute 必須是 :size。',
        'string' => ':attribute 必須是 :size 個字符。',
    ],
    'starts_with' => ':attribute 必須以以下其中一個開始：:values。',
    'string' => ':attribute 必須是一個字符串。',
    'timezone' => ':attribute 必須是一個有效的時區。',
    'unique' => ':attribute 已經被使用。',
    'uploaded' => ':attribute 上傳失敗。',
    'uppercase' => ':attribute 字段必須是大寫。',
    'url' => ':attribute 必須是一個有效的 URL。',
    'ulid' => ':attribute 字段必須是一個有效的 ULID。',
    'uuid' => ':attribute 必須是一個有效的 UUID。',
    'custom' => [
        'attribute-name' => [
            'rule-name' => '自定義訊息',
        ],
    ],
    'attributes' => [],
];
